### ISSUE TITLE
What else needs doing before we're ready to go live

### ISSUE THREAD

**Issue by katiesteckles** [MathsJam/mathsjam-site#16]
- [x] fix all the other issues
- [x] if we can make the colour scheme of the finished site use the cream and primary colours from the SVGs, I think that would look nicest
- [x] can the text in the main bit use more/all of the width of the white bit? looks a bit odd just hunched in the middle, and maybe we can have bigger fonts generally
- [x] Does the map work on the 'find a jam' page?
- [x] I think the edits I've been making on here to page content (particularly in the gathering pages) might need implementing; if they have been, then I need to do some more
- [x] don't want a news page; would need to keep it updated and I won't
- [x] get the latest list of pages/cities from the actual site (#12)
- [x] add Colin's content to the gathering pages (#21)
- [x] city page content looks a bit sparse; should I get all the MathsJams to send me a photo from their event?
- [ ] create a 'how to edit your mathsjam' reference somewhere (#19)
- [ ] check it works on knacky old browsers

If we can get all this done (and I'm happy to find a time we can both work on it together) I'd like to show this to Matt/Colin for approval and put it live.

- [ ] down the line, not necessarily for go: separate organiser page(s), behind a password? (#25)

**Comment by christianp** [comment]
I've made a few new issues - I'd like to have separate tasks to check off - but some of those don't translate directly into things to do so I'll reply below.

> can the text in the main bit use more/all of the width of the white bit? looks a bit odd just hunched in the middle, and maybe we can have bigger fonts generally

According to received wisdom, the optimum line width is 50-60 characters. At the moment it's about 80. Right order of magnitude, but I wouldn't want to go wider. It's hard to pick a font size that works on lots of screens, even if you change based on screen size. I find it comfortable on my desktop screen at the moment - where does it look too small for you?

> Does the map work on the 'find a jam' page?

Do you have a reason to think it doesn't? What's wrong?

> get the latest list of pages/cities from the actual site

I did that on Sunday; see #12 

> city page content looks a bit sparse; should I get all the MathsJams to send me a photo from their event?

Yes, that would be good. The more stuff from cities, the better, but for now it's OK, isn't it? We can't expect every city to send something in.

**Comment by katiesteckles** [comment]
![screen shot 2017-03-14 at 20 30 03](https://cloud.githubusercontent.com/assets/25103599/23921053/1395e328-08f5-11e7-9b65-bc7a46905ffa.png)
There's a chance this is just because I've not got very good signal.

That also shows you the relative widths of things on my screen; maybe it's ok? I don't know. Maybe just the font a little bit bigger, then we'll hit 50-60 chars per line?
